#![doc = "Peripheral access API for STM32H503 microcontrollers (generated using svd2rust v0.36.1 (8654779 2025-07-10))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.36.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn WWDG();
    fn RTC();
    fn TAMP();
    fn RAMCFG();
    fn FLASH();
    fn RCC();
    fn EXTI0();
    fn EXTI1();
    fn EXTI2();
    fn EXTI3();
    fn EXTI4();
    fn EXTI5();
    fn EXTI6();
    fn EXTI7();
    fn EXTI8();
    fn EXTI9();
    fn EXTI10();
    fn EXTI11();
    fn EXTI12();
    fn EXTI13();
    fn EXTI14();
    fn EXTI15();
    fn GPDMA1_CH0();
    fn GPDMA1_CH1();
    fn GPDMA1_CH2();
    fn GPDMA1_CH3();
    fn GPDMA1_CH4();
    fn GPDMA1_CH5();
    fn GPDMA1_CH6();
    fn GPDMA1_CH7();
    fn IWDG();
    fn ADC1();
    fn DAC1();
    fn FDCAN1_IT0();
    fn FDCAN1_IT1();
    fn TIM1_BRK_TERR_IERR();
    fn TIM1_UP();
    fn TIM1_TRG_COM_DIR_IDX();
    fn TIM1_CC();
    fn TIM2();
    fn TIM3();
    fn TIM6();
    fn TIM7();
    fn I2C1_EV();
    fn I2C1_ER();
    fn I2C2_EV();
    fn I2C2_ER();
    fn SPI1();
    fn SPI2();
    fn SPI3();
    fn USART1();
    fn USART2();
    fn USART3();
    fn LPUART1();
    fn LPTIM1();
    fn LPTIM2();
    fn USB_FS();
    fn CRS();
    fn GPDMA2_CH0();
    fn GPDMA2_CH1();
    fn GPDMA2_CH2();
    fn GPDMA2_CH3();
    fn GPDMA2_CH4();
    fn GPDMA2_CH5();
    fn GPDMA2_CH6();
    fn GPDMA2_CH7();
    fn ICACHE();
    fn DTS_WKUP();
    fn RNG();
    fn HASH();
    fn I3C1_EV();
    fn I3C1_ER();
    fn I3C2_EV();
    fn I3C2_ER();
    fn COMP();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 134] = [
    Vector { _handler: WWDG },
    Vector { _reserved: 0 },
    Vector { _handler: RTC },
    Vector { _reserved: 0 },
    Vector { _handler: TAMP },
    Vector { _handler: RAMCFG },
    Vector { _handler: FLASH },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: RCC },
    Vector { _reserved: 0 },
    Vector { _handler: EXTI0 },
    Vector { _handler: EXTI1 },
    Vector { _handler: EXTI2 },
    Vector { _handler: EXTI3 },
    Vector { _handler: EXTI4 },
    Vector { _handler: EXTI5 },
    Vector { _handler: EXTI6 },
    Vector { _handler: EXTI7 },
    Vector { _handler: EXTI8 },
    Vector { _handler: EXTI9 },
    Vector { _handler: EXTI10 },
    Vector { _handler: EXTI11 },
    Vector { _handler: EXTI12 },
    Vector { _handler: EXTI13 },
    Vector { _handler: EXTI14 },
    Vector { _handler: EXTI15 },
    Vector {
        _handler: GPDMA1_CH0,
    },
    Vector {
        _handler: GPDMA1_CH1,
    },
    Vector {
        _handler: GPDMA1_CH2,
    },
    Vector {
        _handler: GPDMA1_CH3,
    },
    Vector {
        _handler: GPDMA1_CH4,
    },
    Vector {
        _handler: GPDMA1_CH5,
    },
    Vector {
        _handler: GPDMA1_CH6,
    },
    Vector {
        _handler: GPDMA1_CH7,
    },
    Vector { _handler: IWDG },
    Vector { _reserved: 0 },
    Vector { _handler: ADC1 },
    Vector { _handler: DAC1 },
    Vector {
        _handler: FDCAN1_IT0,
    },
    Vector {
        _handler: FDCAN1_IT1,
    },
    Vector {
        _handler: TIM1_BRK_TERR_IERR,
    },
    Vector { _handler: TIM1_UP },
    Vector {
        _handler: TIM1_TRG_COM_DIR_IDX,
    },
    Vector { _handler: TIM1_CC },
    Vector { _handler: TIM2 },
    Vector { _handler: TIM3 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: TIM6 },
    Vector { _handler: TIM7 },
    Vector { _handler: I2C1_EV },
    Vector { _handler: I2C1_ER },
    Vector { _handler: I2C2_EV },
    Vector { _handler: I2C2_ER },
    Vector { _handler: SPI1 },
    Vector { _handler: SPI2 },
    Vector { _handler: SPI3 },
    Vector { _handler: USART1 },
    Vector { _handler: USART2 },
    Vector { _handler: USART3 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: LPUART1 },
    Vector { _handler: LPTIM1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: LPTIM2 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: USB_FS },
    Vector { _handler: CRS },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: GPDMA2_CH0,
    },
    Vector {
        _handler: GPDMA2_CH1,
    },
    Vector {
        _handler: GPDMA2_CH2,
    },
    Vector {
        _handler: GPDMA2_CH3,
    },
    Vector {
        _handler: GPDMA2_CH4,
    },
    Vector {
        _handler: GPDMA2_CH5,
    },
    Vector {
        _handler: GPDMA2_CH6,
    },
    Vector {
        _handler: GPDMA2_CH7,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: ICACHE },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: DTS_WKUP },
    Vector { _handler: RNG },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: HASH },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: I3C1_EV },
    Vector { _handler: I3C1_ER },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: I3C2_EV },
    Vector { _handler: I3C2_ER },
    Vector { _handler: COMP },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Window Watchdog interrupt"]
    WWDG = 0,
    #[doc = "2 - RTC global interrupt"]
    RTC = 2,
    #[doc = "4 - TAMP global interrupt"]
    TAMP = 4,
    #[doc = "5 - RAM configuration global interrupt"]
    RAMCFG = 5,
    #[doc = "6 - FLASH non-secure global interrupt"]
    FLASH = 6,
    #[doc = "9 - RCC global interrupt"]
    RCC = 9,
    #[doc = "11 - EXTI Line0 interrupt"]
    EXTI0 = 11,
    #[doc = "12 - EXTI Line1 interrupt"]
    EXTI1 = 12,
    #[doc = "13 - EXTI Line2 interrupt"]
    EXTI2 = 13,
    #[doc = "14 - EXTI Line3 interrupt"]
    EXTI3 = 14,
    #[doc = "15 - EXTI Line4 interrupt"]
    EXTI4 = 15,
    #[doc = "16 - EXTI Line5 interrupt"]
    EXTI5 = 16,
    #[doc = "17 - EXTI Line6 interrupt"]
    EXTI6 = 17,
    #[doc = "18 - EXTI Line7 interrupt"]
    EXTI7 = 18,
    #[doc = "19 - EXTI Line8 interrupt"]
    EXTI8 = 19,
    #[doc = "20 - EXTI Line9 interrupt"]
    EXTI9 = 20,
    #[doc = "21 - EXTI Line10 interrupt"]
    EXTI10 = 21,
    #[doc = "22 - EXTI Line11 interrupt"]
    EXTI11 = 22,
    #[doc = "23 - EXTI Line12 interrupt"]
    EXTI12 = 23,
    #[doc = "24 - EXTI Line13 interrupt"]
    EXTI13 = 24,
    #[doc = "25 - EXTI Line14 interrupt"]
    EXTI14 = 25,
    #[doc = "26 - EXTI Line15 interrupt"]
    EXTI15 = 26,
    #[doc = "27 - GPDMA1 channel 0 global interrupt"]
    GPDMA1_CH0 = 27,
    #[doc = "28 - GPDMA1 channel 1 global interrupt"]
    GPDMA1_CH1 = 28,
    #[doc = "29 - GPDMA1 channel 2 global interrupt"]
    GPDMA1_CH2 = 29,
    #[doc = "30 - GPDMA1 channel 3 global interrupt"]
    GPDMA1_CH3 = 30,
    #[doc = "31 - GPDMA1 channel 4 global interrupt"]
    GPDMA1_CH4 = 31,
    #[doc = "32 - GPDMA1 channel 5 global interrupt"]
    GPDMA1_CH5 = 32,
    #[doc = "33 - GPDMA1 channel 6 global interrupt"]
    GPDMA1_CH6 = 33,
    #[doc = "34 - GPDMA1 channel 7 global interrupt"]
    GPDMA1_CH7 = 34,
    #[doc = "35 - IWDG interrupt"]
    IWDG = 35,
    #[doc = "37 - ADC1 global interrupt"]
    ADC1 = 37,
    #[doc = "38 - DAC1 global interrupt"]
    DAC1 = 38,
    #[doc = "39 - FDCAN1 interrupt 0"]
    FDCAN1_IT0 = 39,
    #[doc = "40 - FDCAN1 interrupt 1"]
    FDCAN1_IT1 = 40,
    #[doc = "41 - TIM1 break/TIM1 transition error/TIM1 index error"]
    TIM1_BRK_TERR_IERR = 41,
    #[doc = "42 - TIM1 Update"]
    TIM1_UP = 42,
    #[doc = "43 - TIM1 trigger and commutation/TIM1 direction change interrupt/TIM1 index"]
    TIM1_TRG_COM_DIR_IDX = 43,
    #[doc = "44 - TIM1 capture compare interrupt"]
    TIM1_CC = 44,
    #[doc = "45 - TIM2 global interrupt"]
    TIM2 = 45,
    #[doc = "46 - TIM3 global interrupt"]
    TIM3 = 46,
    #[doc = "49 - TIM6 global interrupt"]
    TIM6 = 49,
    #[doc = "50 - TIM7 global interrupt"]
    TIM7 = 50,
    #[doc = "51 - I2C1 event interrupt"]
    I2C1_EV = 51,
    #[doc = "52 - I2C1 error interrupt"]
    I2C1_ER = 52,
    #[doc = "53 - I2C2 event interrupt"]
    I2C2_EV = 53,
    #[doc = "54 - I2C2 error interrupt"]
    I2C2_ER = 54,
    #[doc = "55 - SPI1 global interrupt"]
    SPI1 = 55,
    #[doc = "56 - SPI2 global interrupt"]
    SPI2 = 56,
    #[doc = "57 - SPI3 global interrupt"]
    SPI3 = 57,
    #[doc = "58 - USART1 global interrupt"]
    USART1 = 58,
    #[doc = "59 - USART2 global interrupt"]
    USART2 = 59,
    #[doc = "60 - USART3 global interrupt"]
    USART3 = 60,
    #[doc = "63 - LPUART1 global interrupt"]
    LPUART1 = 63,
    #[doc = "64 - LPTIM1 global interrupt"]
    LPTIM1 = 64,
    #[doc = "70 - LPTIM2 global interrupt"]
    LPTIM2 = 70,
    #[doc = "74 - USB OTG FS global interrupt"]
    USB_FS = 74,
    #[doc = "75 - Clock Recovery System global interrupt"]
    CRS = 75,
    #[doc = "90 - GPDMA2 channel 0 global interrupt"]
    GPDMA2_CH0 = 90,
    #[doc = "91 - GPDMA2 channel 1 global interrupt"]
    GPDMA2_CH1 = 91,
    #[doc = "92 - GPDMA2 channel 2 global interrupt"]
    GPDMA2_CH2 = 92,
    #[doc = "93 - GPDMA2 channel 3 global interrupt"]
    GPDMA2_CH3 = 93,
    #[doc = "94 - GPDMA2 channel 4 global interrupt"]
    GPDMA2_CH4 = 94,
    #[doc = "95 - GPDMA2 channel 5 global interrupt"]
    GPDMA2_CH5 = 95,
    #[doc = "96 - GPDMA2 channel 6 global interrupt"]
    GPDMA2_CH6 = 96,
    #[doc = "97 - GPDMA2 channel 7 global interrupt"]
    GPDMA2_CH7 = 97,
    #[doc = "104 - Instruction cache global interrupt"]
    ICACHE = 104,
    #[doc = "113 - DTS interrupt or DTS AIT through EXTI line"]
    DTS_WKUP = 113,
    #[doc = "114 - RNG global interrupt"]
    RNG = 114,
    #[doc = "117 - HASH interrupt"]
    HASH = 117,
    #[doc = "123 - I3C1 event interrupt"]
    I3C1_EV = 123,
    #[doc = "124 - I3C1 error interrupt"]
    I3C1_ER = 124,
    #[doc = "131 - I3C2 event interrupt"]
    I3C2_EV = 131,
    #[doc = "132 - I3C2 error interrupt"]
    I3C2_ER = 132,
    #[doc = "133 - COMP global interrupt"]
    COMP = 133,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Analog to digital converter"]
pub type ADC = crate::Periph<adc::RegisterBlock, 0x4202_8000>;
impl core::fmt::Debug for ADC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ADC").finish()
    }
}
#[doc = "Analog to digital converter"]
pub mod adc;
#[doc = "Comparator"]
pub type COMP = crate::Periph<comp::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for COMP {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("COMP").finish()
    }
}
#[doc = "Comparator"]
pub mod comp;
#[doc = "Cyclic redundancy check calculation unit"]
pub type CRC = crate::Periph<crc::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for CRC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CRC").finish()
    }
}
#[doc = "Cyclic redundancy check calculation unit"]
pub mod crc;
#[doc = "Clock recovery system"]
pub type CRS = crate::Periph<crs::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for CRS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CRS").finish()
    }
}
#[doc = "Clock recovery system"]
pub mod crs;
#[doc = "Digital to analog converter"]
pub type DAC = crate::Periph<dac::RegisterBlock, 0x4202_8400>;
impl core::fmt::Debug for DAC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DAC").finish()
    }
}
#[doc = "Digital to analog converter"]
pub mod dac;
#[doc = "Microcontroller debug unit"]
pub type DBGMCU = crate::Periph<dbgmcu::RegisterBlock, 0x4402_4000>;
impl core::fmt::Debug for DBGMCU {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DBGMCU").finish()
    }
}
#[doc = "Microcontroller debug unit"]
pub mod dbgmcu;
#[doc = "Digital temperature sensor"]
pub type DTS = crate::Periph<dts::RegisterBlock, 0x4000_8c00>;
impl core::fmt::Debug for DTS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DTS").finish()
    }
}
#[doc = "Digital temperature sensor"]
pub mod dts;
#[doc = "Extended interrupt/event controller"]
pub type EXTI = crate::Periph<exti::RegisterBlock, 0x4402_2000>;
impl core::fmt::Debug for EXTI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EXTI").finish()
    }
}
#[doc = "Extended interrupt/event controller"]
pub mod exti;
#[doc = "Controller area network"]
pub type FDCAN1 = crate::Periph<fdcan1::RegisterBlock, 0x4000_a400>;
impl core::fmt::Debug for FDCAN1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FDCAN1").finish()
    }
}
#[doc = "Controller area network"]
pub mod fdcan1;
#[doc = "FLASH address block description"]
pub type FLASH = crate::Periph<flash::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for FLASH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FLASH").finish()
    }
}
#[doc = "FLASH address block description"]
pub mod flash;
#[doc = "General-purpose I/Os"]
pub type GPIOA = crate::Periph<gpioa::RegisterBlock, 0x4202_0000>;
impl core::fmt::Debug for GPIOA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOA").finish()
    }
}
#[doc = "General-purpose I/Os"]
pub mod gpioa;
#[doc = "General-purpose I/Os"]
pub type GPIOB = crate::Periph<gpiob::RegisterBlock, 0x4202_0400>;
impl core::fmt::Debug for GPIOB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOB").finish()
    }
}
#[doc = "General-purpose I/Os"]
pub mod gpiob;
#[doc = "General-purpose I/Os"]
pub type GPIOC = crate::Periph<gpioc::RegisterBlock, 0x4202_0800>;
impl core::fmt::Debug for GPIOC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOC").finish()
    }
}
#[doc = "General-purpose I/Os"]
pub mod gpioc;
#[doc = "General-purpose I/Os"]
pub type GPIOD = crate::Periph<gpioc::RegisterBlock, 0x4202_0c00>;
impl core::fmt::Debug for GPIOD {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOD").finish()
    }
}
#[doc = "General-purpose I/Os"]
pub use self::gpioc as gpiod;
#[doc = "General-purpose I/Os"]
pub type GPIOH = crate::Periph<gpioh::RegisterBlock, 0x4202_1c00>;
impl core::fmt::Debug for GPIOH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOH").finish()
    }
}
#[doc = "General-purpose I/Os"]
pub mod gpioh;
#[doc = "Global privilege controller"]
pub type GTZC1 = crate::Periph<gtzc1::RegisterBlock, 0x4003_2400>;
impl core::fmt::Debug for GTZC1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GTZC1").finish()
    }
}
#[doc = "Global privilege controller"]
pub mod gtzc1;
#[doc = "General purpose direct memory access controller"]
pub type GPDMA1 = crate::Periph<gpdma1::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for GPDMA1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPDMA1").finish()
    }
}
#[doc = "General purpose direct memory access controller"]
pub mod gpdma1;
#[doc = "General purpose direct memory access controller"]
pub type GPDMA2 = crate::Periph<gpdma1::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for GPDMA2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPDMA2").finish()
    }
}
#[doc = "General purpose direct memory access controller"]
pub use self::gpdma1 as gpdma2;
#[doc = "Hash processor"]
pub type HASH = crate::Periph<hash::RegisterBlock, 0x420c_0400>;
impl core::fmt::Debug for HASH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("HASH").finish()
    }
}
#[doc = "Hash processor"]
pub mod hash;
#[doc = "Instruction cache"]
pub type ICACHE = crate::Periph<icache::RegisterBlock, 0x4003_0400>;
impl core::fmt::Debug for ICACHE {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ICACHE").finish()
    }
}
#[doc = "Instruction cache"]
pub mod icache;
#[doc = "Independent watchdog"]
pub type IWDG = crate::Periph<iwdg::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for IWDG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IWDG").finish()
    }
}
#[doc = "Independent watchdog"]
pub mod iwdg;
#[doc = "Inter-integrated circuit"]
pub type I2C1 = crate::Periph<i2c1::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for I2C1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C1").finish()
    }
}
#[doc = "Inter-integrated circuit"]
pub mod i2c1;
#[doc = "Inter-integrated circuit"]
pub type I2C2 = crate::Periph<i2c1::RegisterBlock, 0x4000_5800>;
impl core::fmt::Debug for I2C2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C2").finish()
    }
}
#[doc = "Inter-integrated circuit"]
pub use self::i2c1 as i2c2;
#[doc = "Improved inter-integrated circuit"]
pub type I3C1 = crate::Periph<i3c1::RegisterBlock, 0x4000_5c00>;
impl core::fmt::Debug for I3C1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I3C1").finish()
    }
}
#[doc = "Improved inter-integrated circuit"]
pub mod i3c1;
#[doc = "Improved inter-integrated circuit"]
pub type I3C2 = crate::Periph<i3c1::RegisterBlock, 0x4400_3000>;
impl core::fmt::Debug for I3C2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I3C2").finish()
    }
}
#[doc = "Improved inter-integrated circuit"]
pub use self::i3c1 as i3c2;
#[doc = "Low power timer"]
pub type LPTIM1 = crate::Periph<lptim1::RegisterBlock, 0x4400_4400>;
impl core::fmt::Debug for LPTIM1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LPTIM1").finish()
    }
}
#[doc = "Low power timer"]
pub mod lptim1;
#[doc = "Low power timer"]
pub type LPTIM2 = crate::Periph<lptim1::RegisterBlock, 0x4000_9400>;
impl core::fmt::Debug for LPTIM2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LPTIM2").finish()
    }
}
#[doc = "Low power timer"]
pub use self::lptim1 as lptim2;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type LPUART = crate::Periph<lpuart::RegisterBlock, 0x4400_2400>;
impl core::fmt::Debug for LPUART {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LPUART").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub mod lpuart;
#[doc = "Operational amplifiers"]
pub type OPAMP1 = crate::Periph<opamp1::RegisterBlock, 0x4000_3400>;
impl core::fmt::Debug for OPAMP1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("OPAMP1").finish()
    }
}
#[doc = "Operational amplifiers"]
pub mod opamp1;
#[doc = "Power control"]
pub type PWR = crate::Periph<pwr::RegisterBlock, 0x4402_0800>;
impl core::fmt::Debug for PWR {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PWR").finish()
    }
}
#[doc = "Power control"]
pub mod pwr;
#[doc = "RAMs configuration controller"]
pub type RAMCFG = crate::Periph<ramcfg::RegisterBlock, 0x4002_6000>;
impl core::fmt::Debug for RAMCFG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RAMCFG").finish()
    }
}
#[doc = "RAMs configuration controller"]
pub mod ramcfg;
#[doc = "Reset and clock controller"]
pub type RCC = crate::Periph<rcc::RegisterBlock, 0x4402_0c00>;
impl core::fmt::Debug for RCC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RCC").finish()
    }
}
#[doc = "Reset and clock controller"]
pub mod rcc;
#[doc = "True random number generator"]
pub type RNG = crate::Periph<rng::RegisterBlock, 0x420c_0800>;
impl core::fmt::Debug for RNG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RNG").finish()
    }
}
#[doc = "True random number generator"]
pub mod rng;
#[doc = "Real-time clock"]
pub type RTC = crate::Periph<rtc::RegisterBlock, 0x4400_7800>;
impl core::fmt::Debug for RTC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RTC").finish()
    }
}
#[doc = "Real-time clock"]
pub mod rtc;
#[doc = "System configuration, boot and security"]
pub type SBS = crate::Periph<sbs::RegisterBlock, 0x4400_0400>;
impl core::fmt::Debug for SBS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SBS").finish()
    }
}
#[doc = "System configuration, boot and security"]
pub mod sbs;
#[doc = "Serial peripheral interface"]
pub type SPI1 = crate::Periph<spi1::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for SPI1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI1").finish()
    }
}
#[doc = "Serial peripheral interface"]
pub mod spi1;
#[doc = "Serial peripheral interface"]
pub type SPI2 = crate::Periph<spi1::RegisterBlock, 0x4000_3800>;
impl core::fmt::Debug for SPI2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI2").finish()
    }
}
#[doc = "Serial peripheral interface"]
pub use self::spi1 as spi2;
#[doc = "Serial peripheral interface"]
pub type SPI3 = crate::Periph<spi1::RegisterBlock, 0x4000_3c00>;
impl core::fmt::Debug for SPI3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI3").finish()
    }
}
#[doc = "Serial peripheral interface"]
pub use self::spi1 as spi3;
#[doc = "Tamper and backup registers"]
pub type TAMP = crate::Periph<tamp::RegisterBlock, 0x4400_7c00>;
impl core::fmt::Debug for TAMP {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TAMP").finish()
    }
}
#[doc = "Tamper and backup registers"]
pub mod tamp;
#[doc = "Advanced-control timers"]
pub type TIM1 = crate::Periph<tim1::RegisterBlock, 0x4001_2c00>;
impl core::fmt::Debug for TIM1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM1").finish()
    }
}
#[doc = "Advanced-control timers"]
pub mod tim1;
#[doc = "General-purpose timers"]
pub type TIM2 = crate::Periph<tim2::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for TIM2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM2").finish()
    }
}
#[doc = "General-purpose timers"]
pub mod tim2;
#[doc = "General-purpose timers"]
pub type TIM3 = crate::Periph<tim3::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for TIM3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM3").finish()
    }
}
#[doc = "General-purpose timers"]
pub mod tim3;
#[doc = "Basic timers"]
pub type TIM6 = crate::Periph<tim6::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for TIM6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM6").finish()
    }
}
#[doc = "Basic timers"]
pub mod tim6;
#[doc = "Basic timers"]
pub type TIM7 = crate::Periph<tim7::RegisterBlock, 0x4000_1400>;
impl core::fmt::Debug for TIM7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM7").finish()
    }
}
#[doc = "Basic timers"]
pub mod tim7;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type USART1 = crate::Periph<usart1::RegisterBlock, 0x4001_3800>;
impl core::fmt::Debug for USART1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART1").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub mod usart1;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type USART2 = crate::Periph<usart1::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for USART2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART2").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub use self::usart1 as usart2;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type USART3 = crate::Periph<usart1::RegisterBlock, 0x4000_4800>;
impl core::fmt::Debug for USART3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART3").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub use self::usart1 as usart3;
#[doc = "USB full speed"]
pub type USB = crate::Periph<usb::RegisterBlock, 0x4001_6000>;
impl core::fmt::Debug for USB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USB").finish()
    }
}
#[doc = "USB full speed"]
pub mod usb;
#[doc = "System window watchdog"]
pub type WWDG = crate::Periph<wwdg::RegisterBlock, 0x4000_2c00>;
impl core::fmt::Debug for WWDG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WWDG").finish()
    }
}
#[doc = "System window watchdog"]
pub mod wwdg;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC"]
    pub ADC: ADC,
    #[doc = "COMP"]
    pub COMP: COMP,
    #[doc = "CRC"]
    pub CRC: CRC,
    #[doc = "CRS"]
    pub CRS: CRS,
    #[doc = "DAC"]
    pub DAC: DAC,
    #[doc = "DBGMCU"]
    pub DBGMCU: DBGMCU,
    #[doc = "DTS"]
    pub DTS: DTS,
    #[doc = "EXTI"]
    pub EXTI: EXTI,
    #[doc = "FDCAN1"]
    pub FDCAN1: FDCAN1,
    #[doc = "FLASH"]
    pub FLASH: FLASH,
    #[doc = "GPIOA"]
    pub GPIOA: GPIOA,
    #[doc = "GPIOB"]
    pub GPIOB: GPIOB,
    #[doc = "GPIOC"]
    pub GPIOC: GPIOC,
    #[doc = "GPIOD"]
    pub GPIOD: GPIOD,
    #[doc = "GPIOH"]
    pub GPIOH: GPIOH,
    #[doc = "GTZC1"]
    pub GTZC1: GTZC1,
    #[doc = "GPDMA1"]
    pub GPDMA1: GPDMA1,
    #[doc = "GPDMA2"]
    pub GPDMA2: GPDMA2,
    #[doc = "HASH"]
    pub HASH: HASH,
    #[doc = "ICACHE"]
    pub ICACHE: ICACHE,
    #[doc = "IWDG"]
    pub IWDG: IWDG,
    #[doc = "I2C1"]
    pub I2C1: I2C1,
    #[doc = "I2C2"]
    pub I2C2: I2C2,
    #[doc = "I3C1"]
    pub I3C1: I3C1,
    #[doc = "I3C2"]
    pub I3C2: I3C2,
    #[doc = "LPTIM1"]
    pub LPTIM1: LPTIM1,
    #[doc = "LPTIM2"]
    pub LPTIM2: LPTIM2,
    #[doc = "LPUART"]
    pub LPUART: LPUART,
    #[doc = "OPAMP1"]
    pub OPAMP1: OPAMP1,
    #[doc = "PWR"]
    pub PWR: PWR,
    #[doc = "RAMCFG"]
    pub RAMCFG: RAMCFG,
    #[doc = "RCC"]
    pub RCC: RCC,
    #[doc = "RNG"]
    pub RNG: RNG,
    #[doc = "RTC"]
    pub RTC: RTC,
    #[doc = "SBS"]
    pub SBS: SBS,
    #[doc = "SPI1"]
    pub SPI1: SPI1,
    #[doc = "SPI2"]
    pub SPI2: SPI2,
    #[doc = "SPI3"]
    pub SPI3: SPI3,
    #[doc = "TAMP"]
    pub TAMP: TAMP,
    #[doc = "TIM1"]
    pub TIM1: TIM1,
    #[doc = "TIM2"]
    pub TIM2: TIM2,
    #[doc = "TIM3"]
    pub TIM3: TIM3,
    #[doc = "TIM6"]
    pub TIM6: TIM6,
    #[doc = "TIM7"]
    pub TIM7: TIM7,
    #[doc = "USART1"]
    pub USART1: USART1,
    #[doc = "USART2"]
    pub USART2: USART2,
    #[doc = "USART3"]
    pub USART3: USART3,
    #[doc = "USB"]
    pub USB: USB,
    #[doc = "WWDG"]
    pub WWDG: WWDG,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            ADC: ADC::steal(),
            COMP: COMP::steal(),
            CRC: CRC::steal(),
            CRS: CRS::steal(),
            DAC: DAC::steal(),
            DBGMCU: DBGMCU::steal(),
            DTS: DTS::steal(),
            EXTI: EXTI::steal(),
            FDCAN1: FDCAN1::steal(),
            FLASH: FLASH::steal(),
            GPIOA: GPIOA::steal(),
            GPIOB: GPIOB::steal(),
            GPIOC: GPIOC::steal(),
            GPIOD: GPIOD::steal(),
            GPIOH: GPIOH::steal(),
            GTZC1: GTZC1::steal(),
            GPDMA1: GPDMA1::steal(),
            GPDMA2: GPDMA2::steal(),
            HASH: HASH::steal(),
            ICACHE: ICACHE::steal(),
            IWDG: IWDG::steal(),
            I2C1: I2C1::steal(),
            I2C2: I2C2::steal(),
            I3C1: I3C1::steal(),
            I3C2: I3C2::steal(),
            LPTIM1: LPTIM1::steal(),
            LPTIM2: LPTIM2::steal(),
            LPUART: LPUART::steal(),
            OPAMP1: OPAMP1::steal(),
            PWR: PWR::steal(),
            RAMCFG: RAMCFG::steal(),
            RCC: RCC::steal(),
            RNG: RNG::steal(),
            RTC: RTC::steal(),
            SBS: SBS::steal(),
            SPI1: SPI1::steal(),
            SPI2: SPI2::steal(),
            SPI3: SPI3::steal(),
            TAMP: TAMP::steal(),
            TIM1: TIM1::steal(),
            TIM2: TIM2::steal(),
            TIM3: TIM3::steal(),
            TIM6: TIM6::steal(),
            TIM7: TIM7::steal(),
            USART1: USART1::steal(),
            USART2: USART2::steal(),
            USART3: USART3::steal(),
            USB: USB::steal(),
            WWDG: WWDG::steal(),
        }
    }
}
